### ISSUE TITLE
Make this repo open?

### ISSUE THREAD

**Issue by traversaro** [dic-iit/github-labels#1]
I was looking into propagating the labels from this repo in https://github.com/dic-iit/element_software-engineering, but the instructions seems not to be trivial. I wanted to move them in a GitHub Action so that it would be simple for anyone to propagate them to any repo, but that would be much easier if this repo could be made open rather then private.. Do you think they could be any problem w.r.t. to that? @DanielePucci @Yeshasvitvs

**Comment by DanielePucci** [comment]
For me it is ok @traversaro !

**Comment by traversaro** [comment]
@Yeshasvitvs did you agree to open this repo? Thanks!

**Comment by yeshasvitirupachuri** [comment]
@traversaro Sure

**Comment by traversaro** [comment]
Thanks, done!
